### ISSUE TITLE
docker compose 파일을 여러개 사용하기

### ISSUE THREAD

**Issue by BOKJUNSOO** [BOKJUNSOO/kafka-study#2]
🎈 docker로 하나의 서버만 독립적인 디렉토리에서 사용해왔기 때문에 여러개의 컴포즈 파일이 존재하는 디렉토리에서 컴포즈 파일을 사용하는 방법에 대해서 처음 알게 됐습니다.

여기서 
`-p` 는 아마 `project` 의 플래그를 따온것 같고
`-f` 은 compose 명령어의 특정 `file`을 지정해주겠다는 플래그를 사용하는것 같습니다!

```bash
docker compose -p 컨테이너명 -f 특정컴포즈파일 up --build -d
```

🎈 추가로 .. `context` 문법

docker compose yaml 파일 작성시 `context` 속성의 정체는 사실
`어떤 프로젝트의 루트 디렉터리`를 나타내는 것이었습니다.
단순히 dockerfile을 찾는데에 사용하는 줄 알았으나 그게 아니었습니다.
```yaml
  build:
    context: ../airflow
    dockerfile: ../airflow/Dockerfile.airflow
```
